###
@host = http://localhost:8080
GET {{host}}/login
###
GET {{host}}/chat
###
POST {{host}}/login?username=user&password=password&_csrf=2aaf0fce-656e-47d1-b762-eab0920aba0f
###
POST {{host}}/login?username=login&password=password&_csrf=64394de7-67d9-483d-af7a-2af396996476
###
POST {{host}}/room/add
Content-Type: application/json
X-CSRF-TOKEN: a765d588-77c4-4f29-9741-ba3dc52ff5b3

{
    "title": "newRoom34567"
}
###
POST {{host}}/room/update
Content-Type: application/json
X-CSRF-TOKEN: 67c97e2d-0ebc-418d-a22f-0f9681be4871

{
    "id": 4,
    "title": "newRoom"
}
###
POST {{host}}/room/delete/5
X-CSRF-TOKEN: 67c97e2d-0ebc-418d-a22f-0f9681be4871
###
POST {{host}}/room/2/participant/add/1
X-CSRF-TOKEN: a765d588-77c4-4f29-9741-ba3dc52ff5b3
###
POST {{host}}/room/2/participant/delete/1
X-CSRF-TOKEN: a765d588-77c4-4f29-9741-ba3dc52ff5b3
###
GET {{host}}/room/2/participant
###
POST {{host}}/logout
X-CSRF-TOKEN: 67c97e2d-0ebc-418d-a22f-0f9681be4871