###
@host = http://localhost:8080
GET {{host}}/login
###
POST {{host}}/login?username=lol&password=lel&_csrf=0e65704b-c836-47aa-bc33-a09e72c95310
###
POST {{host}}/login?username=lol&password=lel&_csrf=feee9871-4a02-4fa8-b52a-ede2a6355f3d
